### ISSUE TITLE
Possible compatibility issue with composer ^2.0?

### ISSUE THREAD

**Issue by jacklowrie** [lukasbesch/bedrock-plugin-disabler#14]
Hi,

I tried installing this via composer to a fresh Bedrock install and ran into an issue - seems like there might be a compatibility issue with composer 2.x? 

Here's the output I see when I run `composer require lukasbesch/bedrock-plugin-disabler`:

```sh
Your requirements could not be resolved to an installable set of packages.

 Problem 1
    - Root composer.json requires lukasbesch/bedrock-plugin-disabler ^1.2 -> satisfiable by lukasbesch/bedrock-plugin-disabler[v1.2.0, v1.2.1].
    - lukasbesch/bedrock-plugin-disabler[v1.2.0, ..., v1.2.1] require composer/installers ^1.4 -> found composer/installers[v1.4.0, ..., 1.x-dev] but it conflicts with your root composer.json require (^2.1).
```

And my `composer.json`:
```json
  "require": {
    "php": ">=7.4",
    "composer/installers": "^2.1",
    "vlucas/phpdotenv": "^5.4",
    "oscarotero/env": "^2.1",
    "roots/bedrock-autoloader": "^1.0",
    "roots/bedrock-disallow-indexing": "^2.0",
    "roots/wordpress": "5.9.3",
    "roots/wp-config": "1.0.0",
    "roots/wp-password-bcrypt": "1.1.0"
  },
```

**Comment by lukasbesch** [comment]
Thanks @jacklowrie for the report. How could I miss this one?

In the current version [1.3.1](https://github.com/lukasbesch/bedrock-plugin-disabler/releases/tag/v1.3.1) the `composer.json` supports `composer/installers: ^1.4 | ^2.0`. The `composer.lock` is now removed from the repository, as `composer/installers` is the one and only dependency – and it should always work.

If you're still having troubles please reopen.
